"""
Generated by Claude 3.5 Sonnet

Prompt:
Make a python script that reads emails.txt file which has a new email on each line and make two new files yahoo.txt and aol.txt
These files contain all the emails that end with @yahoo.com and @aol.com from the given list of emails
Also make sure that only the valid emails are added to these files
And then make a last other-mails.txt file that contains all other valid emails which are not @yahoo.com and @aol.com
"""


import re

def is_valid_email(email):
    """
    Validate email using regex pattern.
    Returns True if email is valid, False otherwise.
    """
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return bool(re.match(pattern, email.strip()))

def sort_emails(input_file):
    """
    Read emails from input file and sort them into different files based on domain.
    Only valid emails are included.
    """
    yahoo_emails = []
    aol_emails = []
    other_emails = []
    
    # Read and process emails
    try:
        with open(input_file, 'r') as f:
            for line in f:
                email = line.strip()
                if is_valid_email(email):
                    if email.lower().endswith('@yahoo.com'):
                        yahoo_emails.append(email)
                    elif email.lower().endswith('@aol.com'):
                        aol_emails.append(email)
                    else:
                        other_emails.append(email)
    except FileNotFoundError:
        print(f"Error: Could not find {input_file}")
        return
    except Exception as e:
        print(f"Error reading file: {e}")
        return
    
    # Write sorted emails to respective files
    try:
        # Write Yahoo emails
        with open('yahoo.txt', 'w') as f:
            f.write('\n'.join(yahoo_emails))
        
        # Write AOL emails
        with open('aol.txt', 'w') as f:
            f.write('\n'.join(aol_emails))
        
        # Write other emails
        with open('other-mails.txt', 'w') as f:
            f.write('\n'.join(other_emails))
            
        print(f"Successfully processed emails:")
        print(f"Yahoo emails: {len(yahoo_emails)}")
        print(f"AOL emails: {len(aol_emails)}")
        print(f"Other emails: {len(other_emails)}")
            
    except Exception as e:
        print(f"Error writing to output files: {e}")

if __name__ == "__main__":
    sort_emails('emails.txt')